### ISSUE TITLE
ValueError: pickle protocol 4 asked for; the highest available protocol is 2

### ISSUE THREAD

**Issue by jyn514** [grantjenks/python-diskcache#134]
This is with `Python 2.7.15+`, your library works great with python3 :)

```
Traceback (most recent call last):
  ... snip ...
  File "/home/joshua/Documents/Programming/python/grepme/grepme/http.py", line 35, in get
    val = CACHE.get(key)
  File "/home/joshua/.local/lib/python2.7/site-packages/diskcache/core.py", line 1174, in get
    db_key, raw = self._disk.put(key)
  File "/home/joshua/.local/lib/python2.7/site-packages/diskcache/core.py", line 194, in put
    data = pickle.dumps(key, protocol=self.pickle_protocol)
ValueError: pickle protocol 4 asked for; the highest available protocol is 2
```

```
$ pip freeze | grep diskcache
diskcache==4.0.0
```

**Comment by grantjenks** [comment]
Are you using the same cache across Python 2 and Python 3? If so you need to set the pickle level to 2 in your Python 3 code. It looks like Python 3 was used to store an item but Python 2 is being used to access it.

**Comment by jyn514** [comment]
Hmm I thought I removed the cache altogether before trying this ... let me see if my own code is buggy haha

**Comment by jyn514** [comment]
Ah yup this is a bug in my code. Sorry about that!

**Comment by abubelinha** [comment]
I was also interested in this because I sync my code between two computers (home/work) with different Python versions (3.8 uses pickle 5 / 3.4 uses pickle <=4). So I got this error when running script at work:

```Python
  File "c:\python34\lib\site-packages\diskcache\core.py", line 1874, in wrapper
    result = self.get(key, default=ENOVAL, retry=True)
  File "c:\python34\lib\site-packages\diskcache\fanout.py", line 281, in get
    index = self._hash(key) % self._count
  File "c:\python34\lib\site-packages\diskcache\core.py", line 126, in hash
    disk_key, _ = self.put(key)
  File "c:\python34\lib\site-packages\diskcache\core.py", line 161, in put
    data = pickle.dumps(key, protocol=self.pickle_protocol)
ValueError: pickle protocol must be <= 4
```

I solved it now with this:

```Python
from diskcache import Cache
cache = Cache()
cache.disk_pickle_protocol = 4
# also valid:  
cache = Cache(disk_pickle_protocol = 4)
```

@abubelinha
