### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by Bhupesh-V** [grantjenks/python-diskcache#139]
I tried using diskcache in `ThreadPoolExecutor` but the following error is raised

The error trace
```bash
Traceback (most recent call last):
  File "demo.py", line 34, in <module>
    results = list(executor.map(get_feed, [key for key in urls]))
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "demo.py", line 30, in get_feed
    return __manage_cache(url)
  File "demo.py", line 23, in __manage_cache
    cache.add(url, parsed_feed, expire=3600)
  File "/home/bhupesh/Documents/defe/lib/python3.6/site-packages/diskcache/core.py", line 1025, in add
    size, mode, filename, db_value = self._disk.store(value, read, key=key)
  File "/home/bhupesh/Documents/defe/lib/python3.6/site-packages/diskcache/core.py", line 263, in store
    result = pickle.dumps(value, protocol=self.pickle_protocol)
ValueError: I/O operation on closed file.
```

the code I am executing

```python
from diskcache import Cache
from concurrent.futures import ThreadPoolExecutor
import feedparser

urls = [
    "https://techcrunch.com/feed/",
    "https://www.geekwire.com/feed/",
    "https://www.technology.org/feed/"
]


def __manage_cache(url: str):
    cache = Cache(".feedcache")
    if url in cache:
        print("hit")
        data = cache.get(url)
    else:
        print("miss")
        parsed_feed = feedparser.parse(url)
        print("new feed")
        # feedparser returns a list of dicts
        cache.add(url, parsed_feed, expire=3600)
        data = parsed_feed
    cache.close()
    return data


def get_feed(url: str):
    return __manage_cache(url)


with ThreadPoolExecutor(max_workers=10) as executor:
    results = list(executor.map(get_feed, [key for key in urls]))

print(results)
```

**Comment by grantjenks** [comment]
I have not had a chance to run it myself but it looks like it errors on pickle. Pickle is Python’s built-in serialization library. DiskCache isn’t doing any IO on the line that throws the exception. So my guess is that the data returned by feedparser has a file handle reference (perhaps through lxml). File handles cannot be serialized, therefore it errors.
