### ISSUE TITLE
Readme file is not pure ascii

### ISSUE THREAD

**Issue by Baughn** [grantjenks/python-diskcache#14]
Which leads to errors like this:
```
➜  sv-tools  nix-shell                                                                         ~/dev/sv-tools
these derivations will be built:
  /nix/store/ilvmx3q5bfjqmhc1sarzrlwvbvfc4rly-python-diskcache-v1.6.6-src.drv
  /nix/store/8lmqbi0j8xc2xhvgvl3xqldixgibsg5x-python3.5-diskcache-1.6.6.drv
building path(s) ‘/nix/store/999v4wbl7ycvg3355p66sfnjjj01k2rs-python-diskcache-v1.6.6-src’

trying https://github.com/grantjenks/python-diskcache/archive/v1.6.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   135    0   135    0     0    258      0 --:--:-- --:--:-- --:--:--   258
100  406k  100  406k    0     0   262k      0  0:00:01  0:00:01 --:--:-- 1278k
unpacking source archive /tmp/nix-build-python-diskcache-v1.6.6-src.drv-0/v1.6.6.tar.gz
building path(s) ‘/nix/store/cxsbysaqka3312a5wlmpwwdxn8l1zsc4-python3.5-diskcache-1.6.6’
unpacking sources
unpacking source archive /nix/store/999v4wbl7ycvg3355p66sfnjjj01k2rs-python-diskcache-v1.6.6-src
source root is python-diskcache-v1.6.6-src
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file python-diskcache-v1.6.6-src/tox.ini
patching sources
configuring
building
Traceback (most recent call last):
  File "nix_run_setup.py", line 6, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 19, in <module>
    readme = reader.read()
  File "/nix/store/w9gwivwr7ih57b4y1dfhv64xy316p5qn-python3-3.5.1/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1068: ordinal not in range(128)
builder for ‘/nix/store/8lmqbi0j8xc2xhvgvl3xqldixgibsg5x-python3.5-diskcache-1.6.6.drv’ failed with exit code 1
error: build of ‘/nix/store/8lmqbi0j8xc2xhvgvl3xqldixgibsg5x-python3.5-diskcache-1.6.6.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

A quick fix would be to set the encoding to utf-8 on open.

**Comment by grantjenks** [comment]
Fixed at a743b06 and deployed at 1.6.7
