### ISSUE TITLE
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by lukesavva** [grantjenks/python-diskcache#235]
I am consistently getting the error 
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at LiteDB.FileDiskService.SetLength(Int64 fileSize)
   at LiteDB.TransactionService.PersistDirtyPages()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Update(String collection, BsonDocument doc)
   at LiteDB.LiteFileStream.Dispose(Boolean disposing)
   at LiteDB.LiteFileStream.Finalize()

Then the instance of python crashes and shuts down.

**Comment by lukesavva** [comment]
Ignore this, just realised it is coming from a different library!!
