### ISSUE TITLE
TypeError: cannot pickle 'memoryview' object

### ISSUE THREAD

**Issue by Quamber** [grantjenks/python-diskcache#261]
`import copy
import datetime

import numpy as np
import pandas as pd
import os
from functions import functions_util as util

from diskcache import Cache

cache = Cache("_cache")

# load dimensions and facts tables
@cache.memoize(typed=True,expire=datetime.timedelta(hours=2).total_seconds() if os.environ["LOCAL"]=='true' else 0)
def load_data():
        // Some processing

`

**a simple implementation of example is causing me this issue**

Traceback (most recent call last):
  File "/daily_job.py", line 5, in <module>
    basic()
  File "/basic_frameworks.py", line 19, in main
   Dataframe1, DataFrame2 = cen_dbc.load_data()
  File "/Users/quamber.ali/Library/Caches/pypoetry/virtualenvs/consolidated-0Ob4nCDC-py3.9/lib/python3.9/site-packages/diskcache/core.py", line 1879, in wrapper
    self.set(key, result, expire, tag=tag, retry=True)
  File "/Users/quamber.ali/Library/Caches/pypoetry/virtualenvs/consolidated-0Ob4nCDC-py3.9/lib/python3.9/site-packages/diskcache/core.py", line 772, in set
    size, mode, filename, db_value = self._disk.store(value, read, key=key)
  File "/Users/quamber.ali/Library/Caches/pypoetry/virtualenvs/consolidated-0Ob4nCDC-py3.9/lib/python3.9/site-packages/diskcache/core.py", line 221, in store
    result = pickle.dumps(value, protocol=self.pickle_protocol)
TypeError: cannot pickle 'memoryview' object

**Comment by grantjenks** [comment]
Looks like a limitation of pickle. Use a different serialization tool.

**Comment by Quamber** [comment]
Not using it within my function so it must be in the library. How to change that in @memoize as i see no option.

**Comment by grantjenks** [comment]
https://grantjenks.com/docs/diskcache/tutorial.html#disk
