### ISSUE TITLE
PicklingError: logger cannot be pickled

### ISSUE THREAD

**Issue by gadelkareem** [grantjenks/python-diskcache#302]
Here is my code:

> logger.py
```python
import logging
import os

LOG_LEVEL = os.environ.get("LOG_LEVEL", logging.INFO)


class Logger(logging.Logger):
    def __init__(self, name, level=logging.NOTSET):
        super().__init__(name, level)
        self._configure_logging()

    def _configure_logging(self):
        log_level = LOG_LEVEL.upper()
        numeric_level = getattr(logging, log_level, None)
        if not isinstance(numeric_level, int):
            raise ValueError(f"Invalid log level: {log_level}")

        self.setLevel(numeric_level)
        formatter = logging.Formatter(
            "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        )
        handler = logging.StreamHandler()
        handler.setFormatter(formatter)
        self.addHandler(handler)
        if log_level == "DEBUG":
            self.debug("Debug mode is enabled.")

    def rename(self, name):
        self.name = name
```

> summariser.py
```python
from diskcache import Cache
import logger

cache = Cache(".diskcache")

class Summariser:

    def __init__(self, bot):
        self.log = logger.Logger("summariser")
        self.current_path = os.path.dirname(os.path.realpath(__file__))

    @cache.memoize()
    def summarise(self, file_path, message=None, counter=0):
        response = self.process(
            attachments=[file_path],
            message=message,
        )
        if not response:
            self.log.warning(
                f"no response"
            )
            if counter == 0:
                  return self.summarise(
                      file_path=None,
                      message=message,
                      counter=counter + 1,
                  )

            raise Exception(
                f"no response"
            )
        return response

```

I am getting this error:
```
Exception: logger cannot be pickled
Traceback (most recent call last):
  File "summarise.py", line 154, in process_file
    summary_txt = self.summarise(file_path=file_path)
  File "lib/python3.10/site-packages/diskcache/core.py", line 1872, in wrapper
    result = self.get(key, default=ENOVAL, retry=True)
  File "lib/python3.10/site-packages/diskcache/core.py", line 1149, in get
    db_key, raw = self._disk.put(key)
  File "lib/python3.10/site-packages/diskcache/core.py", line 161, in put
    data = pickle.dumps(key, protocol=self.pickle_protocol)
  File "lib/python3.10/logging/__init__.py", line 1774, in __reduce__
    raise pickle.PicklingError('logger cannot be pickled')
_pickle.PicklingError: logger cannot be pickled
```

Might related to https://bugs.python.org/issue30520

**Comment by grantjenks** [comment]
Based on the error message: loggers can't be pickled. DiskCache uses pickle by default to serialize objects. You'll need to remove the logger from the class attributes or use a different serializer. (I doubt there is a serializer that can work here.)

**Comment by gadelkareem** [comment]
But why does the diskcache serialise the logger? I only need the response text if any...

**Comment by grantjenks** [comment]
The first argument to `summarise` is `self` which is a reference to a `Summariser`.

**Comment by gadelkareem** [comment]
is there a way to ignore that parameter?

**Comment by grantjenks** [comment]
You're not using "self" as a keyword argument. Try `ignore=(0, 'counter')`. I'm not sure how you're using the `counter` argument.

**Comment by gadelkareem** [comment]
Thanks for the quick support!
